{% set name = "hatch" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hatch-{{ version }}.tar.gz
  sha256: 351e41bc6c72bc93cb98651212226e495b43549eee27c487832e459e5d0f0eda

build:
  noarch: python
  script: sed -i '/"uv/d' ./pyproject.toml && {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatch = hatch.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.21.0
    - hatch-vcs >=0.4.0
  run:
    - click >=8.0.6
    - hatchling >=1.24.2
    - httpx >=0.22.0
    - hyperlink >=21.0.0
    - keyring >=23.5.0
    - packaging >=23.2
    - pexpect >=4.8,<5
    - platformdirs >=2.5.0
    - python >=3.8
    - rich >=11.2.0
    - shellingham >=1.4.0
    - tomli-w >=1.0
    - tomlkit >=0.11.1
    - userpath >=1.7,<2
    - virtualenv >=20.26.1
    - uv >=0.1.35
    - zstandard <1.0

test:
  source_files:
    - tests
    - pyproject.toml
    - hatch.toml
  imports:
    - hatch
  commands:
    - hatch --help
    - pip check
    - pytest --ignore tests/backend -ra -k "not test_already_installed_update_flag and not test_already_installed_update_prompt and not test_installation and not test_all and not test_pypirc"
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-xdist
    - pyfakefs
    - git
    - rust

about:
  home: https://hatch.pypa.io/latest/
  summary: Modern, extensible Python project management
  dev_url: https://github.com/pypa/hatch
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ofek
    - henryiii
