{% set name = "hatch" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch-{{ version }}.tar.gz
  sha256: 7afc701fd5b33684a6650e1ecab8957e19685f824240ba7458dcacd66f90fb46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatch = hatch.cli:main

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.14.0
  run:
    - click >=8.0.3
    - hatchling >=1.14.0
    - httpx >=0.22.0
    - hyperlink >=21.0.0
    - keyring >=23.5.0
    - pexpect >=4.8
    - platformdirs >=2.5.0
    - pyperclip >=1.8.2
    - python >=3.7
    - rich >=11.2.0
    - shellingham >=1.4.0
    - tomli-w >=1.0
    - tomlkit >=0.10.1
    - userpath >=1.7
    - virtualenv >=20.13.1

test:
  imports:
    - hatch
  commands:
    - pip check
    - hatch --help
  requires:
    - pip

about:
  home: https://hatch.pypa.io/latest/
  summary: Modern, extensible Python project management
  dev_url: https://github.com/pypa/hatch
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ofek
