{% set name = "hatch" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hatch-{{ version }}.tar.gz
  sha256: fdc574184dcb1d52a63a3cfd08431bf674ad3be2fd7316cbf5fb6d4bdbc3032f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - hatch = hatch.cli:main

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.19.0
    - hatch-vcs >=0.4.0
  run:
    - click >=8.0.6
    - hatchling >=1.19.0
    - httpx >=0.22.0
    - hyperlink >=21.0.0
    - keyring >=23.5.0
    - pexpect >=4.8
    - platformdirs >=2.5.0
    - python >=3.8
    - rich >=11.2.0
    - shellingham >=1.4.0
    - tomli-w >=1.0
    - tomlkit >=0.10.1
    - userpath >=1.7
    - virtualenv >=20.13.1
    - zstandard <1.0

test:
  imports:
    - hatch
  commands:
    - pip check
    - hatch --help
  requires:
    - pip

about:
  home: https://hatch.pypa.io/latest/
  summary: Modern, extensible Python project management
  dev_url: https://github.com/pypa/hatch
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ofek
