context:
  name: hatch
  version: "1.16.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/hatch-${{ version }}.tar.gz
  sha256: f288938da85b4b90e47d94788e19e9976dcd6fd53b48343ea251a2a37256a980

build:
  number: 0
  noarch: python
  script: sed -i '/"uv/d' ./pyproject.toml && python -m pip install . -v
  python:
    entry_points:
      - hatch = hatch.cli:main

requirements:
  host:
    - pip
    - python  ${{ python_min }}.*
    - hatchling >=1.21.0
    - hatch-vcs >=0.4.0
  run:
    - click >=8.0.6
    - hatchling >=1.27.0
    - httpx >=0.22.0
    - hyperlink >=21.0.0
    - keyring >=23.5.0
    - packaging >=24.2
    - pexpect >=4.8,<5
    - platformdirs >=2.5.0
    - pyproject_hooks
    - python >=${{ python_min }}
    - rich >=11.2.0
    - shellingham >=1.4.0
    - tomli-w >=1.0
    - tomlkit >=0.11.1
    - userpath >=1.7,<2
    - uv >=0.5.23
    - virtualenv >=20.26.6
    - backports.zstd >=1

tests:
  - python:
      imports:
        - hatch
  - files:
      source:
        - tests
        - pyproject.toml
        - hatch.toml
    requirements:
      run:
        - flit-core
        - pip
        - pytest
        - pytest-mock
        - pytest-xdist
        - python ${{ python_min }}.*
        - pyfakefs
        - git
        - rust
    script:
      - hatch --help
      - pip check
      - pytest --ignore tests/backend -ra -k "not test_already_installed_update_flag and not test_already_installed_update_prompt and not test_installation and not test_all and not test_pypirc"

about:
  summary: Modern, extensible Python project management
  license: MIT
  license_file: LICENSE.txt
  homepage: https://hatch.pypa.io/latest/
  repository: https://github.com/pypa/hatch

extra:
  recipe-maintainers:
    - ofek
    - henryiii
